services:
  app:
    build: .
    image: devlink-backend
    container_name: devlink_app
    restart: always
    network_mode: host
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JPA_DDL_AUTO: ${JPA_DDL_AUTO:-validate}
      SERVER_PORT: ${SERVER_PORT:-8080}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-86400000}

