spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/linkdev_db}
spring.datasource.username=${DB_USERNAME:linkdev_admin}
spring.datasource.password=${DB_PASSWORD:x9+lFj3vY42r}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT:8080}

app.jwt.secret=${JWT_SECRET:GdgQLdo7xLff9qSLaM8PFqvVJ4IJrmvqoPdG2NKc6iY}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}